version: '3.8'
services:
  pg:
    image: postgres:14-alpine
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=mYAw3s0meB!log
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/migrations

volumes:
  pg-data:
